theme: jekyll-theme-minimal

title: Jeongsoo Kim
# logo: /profile.jpg
description: >
  M.S. in Computer Science<br>
  (Sogang University)<br>
  <br>
  📍 Hiroshima, Japan<br>
  ✉️ <a href="mailto:jskim1@sogang.ac.kr">jskim1@sogang.ac.kr</a><br>
  🎓 <a href="https://scholar.google.com/citations?user=NqAtWGQAAAAJ&hl=enD" target="_blank"
