theme: jekyll-theme-minimal

title: Jeongsoo Kim
logo: /assets/pic.jpg
description: >
  M.S. in Computer Science<br>
  (Sogang University)<br>
  <br>
  📍 Hiroshima, Japan<br>
  ✉️ E-Mail <a href="mailto:jeongskim512@gmail.com">jeongskim512@gmail.com</a><br>
  🎓 Google Scholar <a href="https://scholar.google.com/citations?user=NqAtWGQAAAAJ&hl=en" target="_blank">Link</a>
