theme: jekyll-theme-minimal

title: Jeongsoo Kim
logo: '<img src="/assets/pic.jpg" alt="Profile" style="width: 150px; border-radius: 50%; display: block; margin: 0 auto;">'
description: >
  M.S. in Computer Science<br>
  (Sogang University)<br>
  <br>
  📍 Hiroshima, Japan<br>
  ✉️ E-Mail <a href="mailto:jeongskim512@gmail.com">jeongskim512@gmail.com</a><br>
  🎓 Google Scholar <a href="https://scholar.google.com/citations?user=NqAtWGQAAAAJ&hl=en" target="_blank">Link</a>
